name: storybook_flutter_test
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  meta: ^1.9.1
  storybook_flutter: ^0.12.0

dev_dependencies:
  mews_pedantic: ^0.16.0

flutter:
  uses-material-design: true
